name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirement.txt
          python process_data.py
          python train.py 

          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md

          echo "## Data Viz." > report.md
          echo '![inline](feature_importance.png)' >> report.md
          echo '![inline](confusion_matrix.png)' >> report.md
          cml comment create report.md
         
